name: Build macOS app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter
          pip install py2app

      - name: Build app
        run: |
          python setup.py py2app

      - name: Upload built app
        uses: actions/upload-artifact@v2
        with:
          name: CipherX-Beta
          path: dist/
